/* 
 * Netilion API Documentation
 *
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Netilion.Api.Client.SwaggerDateConverter;

namespace Netilion.Api.Model
{
    /// <summary>
    /// DataExportsResponse
    /// </summary>
    [DataContract]
        public partial class DataExportsResponse :  IEquatable<DataExportsResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DataExportsResponse" /> class.
        /// </summary>
        /// <param name="dataExports">dataExports.</param>
        public DataExportsResponse(List<DataExportResponse> dataExports = default(List<DataExportResponse>))
        {
            this.DataExports = dataExports;
        }
        
        /// <summary>
        /// Gets or Sets DataExports
        /// </summary>
        [DataMember(Name="data_exports", EmitDefaultValue=false)]
        public List<DataExportResponse> DataExports { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DataExportsResponse {\n");
            sb.Append("  DataExports: ").Append(DataExports).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DataExportsResponse);
        }

        /// <summary>
        /// Returns true if DataExportsResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of DataExportsResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DataExportsResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.DataExports == input.DataExports ||
                    this.DataExports != null &&
                    input.DataExports != null &&
                    this.DataExports.SequenceEqual(input.DataExports)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DataExports != null)
                    hashCode = hashCode * 59 + this.DataExports.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
