/* 
 * Netilion API Documentation
 *
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Netilion.Api.Client.SwaggerDateConverter;

namespace Netilion.Api.Model
{
    /// <summary>
    /// Array of specification keys
    /// </summary>
    [DataContract]
        public partial class SpecificationKeys :  IEquatable<SpecificationKeys>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SpecificationKeys" /> class.
        /// </summary>
        /// <param name="specificationKeys">specificationKeys (required).</param>
        public SpecificationKeys(List<string> specificationKeys = default(List<string>))
        {
            // to ensure "specificationKeys" is required (not null)
            if (specificationKeys == null)
            {
                throw new InvalidDataException("specificationKeys is a required property for SpecificationKeys and cannot be null");
            }
            else
            {
                this._SpecificationKeys = specificationKeys;
            }
        }
        
        /// <summary>
        /// Gets or Sets _SpecificationKeys
        /// </summary>
        [DataMember(Name="specification_keys", EmitDefaultValue=false)]
        public List<string> _SpecificationKeys { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SpecificationKeys {\n");
            sb.Append("  _SpecificationKeys: ").Append(_SpecificationKeys).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SpecificationKeys);
        }

        /// <summary>
        /// Returns true if SpecificationKeys instances are equal
        /// </summary>
        /// <param name="input">Instance of SpecificationKeys to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SpecificationKeys input)
        {
            if (input == null)
                return false;

            return 
                (
                    this._SpecificationKeys == input._SpecificationKeys ||
                    this._SpecificationKeys != null &&
                    input._SpecificationKeys != null &&
                    this._SpecificationKeys.SequenceEqual(input._SpecificationKeys)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this._SpecificationKeys != null)
                    hashCode = hashCode * 59 + this._SpecificationKeys.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
