/* 
 * Netilion API Documentation
 *
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Netilion.Api.Api;
using Netilion.Api.Model;
using Netilion.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Netilion.Api.Test
{
    /// <summary>
    ///  Class for testing AssetHistory
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AssetHistoryTests
    {
        // TODO uncomment below to declare an instance variable for AssetHistory
        //private AssetHistory instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AssetHistory
            //instance = new AssetHistory();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AssetHistory
        /// </summary>
        [Test]
        public void AssetHistoryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AssetHistory
            //Assert.IsInstanceOfType<AssetHistory> (instance, "variable 'instance' is a AssetHistory");
        }


        /// <summary>
        /// Test the property 'Asset'
        /// </summary>
        [Test]
        public void AssetTest()
        {
            // TODO unit test for the property 'Asset'
        }
        /// <summary>
        /// Test the property 'Datetime'
        /// </summary>
        [Test]
        public void DatetimeTest()
        {
            // TODO unit test for the property 'Datetime'
        }

    }

}
