/* 
 * Netilion API Documentation
 *
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Netilion.Api.Api;
using Netilion.Api.Model;
using Netilion.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Netilion.Api.Test
{
    /// <summary>
    ///  Class for testing AssetKeyValuesResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AssetKeyValuesResponseTests
    {
        // TODO uncomment below to declare an instance variable for AssetKeyValuesResponse
        //private AssetKeyValuesResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AssetKeyValuesResponse
            //instance = new AssetKeyValuesResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AssetKeyValuesResponse
        /// </summary>
        [Test]
        public void AssetKeyValuesResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AssetKeyValuesResponse
            //Assert.IsInstanceOfType<AssetKeyValuesResponse> (instance, "variable 'instance' is a AssetKeyValuesResponse");
        }


        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Test]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'Unit'
        /// </summary>
        [Test]
        public void UnitTest()
        {
            // TODO unit test for the property 'Unit'
        }
        /// <summary>
        /// Test the property 'Group'
        /// </summary>
        [Test]
        public void GroupTest()
        {
            // TODO unit test for the property 'Group'
        }
        /// <summary>
        /// Test the property 'Latest'
        /// </summary>
        [Test]
        public void LatestTest()
        {
            // TODO unit test for the property 'Latest'
        }
        /// <summary>
        /// Test the property 'Max'
        /// </summary>
        [Test]
        public void MaxTest()
        {
            // TODO unit test for the property 'Max'
        }
        /// <summary>
        /// Test the property 'Min'
        /// </summary>
        [Test]
        public void MinTest()
        {
            // TODO unit test for the property 'Min'
        }
        /// <summary>
        /// Test the property 'Mean'
        /// </summary>
        [Test]
        public void MeanTest()
        {
            // TODO unit test for the property 'Mean'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Pagination'
        /// </summary>
        [Test]
        public void PaginationTest()
        {
            // TODO unit test for the property 'Pagination'
        }

    }

}
