/* 
 * Netilion API Documentation
 *
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Netilion.Api.Api;
using Netilion.Api.Model;
using Netilion.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Netilion.Api.Test
{
    /// <summary>
    ///  Class for testing EdgeDeviceResponseApiSubscription
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EdgeDeviceResponseApiSubscriptionTests
    {
        // TODO uncomment below to declare an instance variable for EdgeDeviceResponseApiSubscription
        //private EdgeDeviceResponseApiSubscription instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EdgeDeviceResponseApiSubscription
            //instance = new EdgeDeviceResponseApiSubscription();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EdgeDeviceResponseApiSubscription
        /// </summary>
        [Test]
        public void EdgeDeviceResponseApiSubscriptionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EdgeDeviceResponseApiSubscription
            //Assert.IsInstanceOfType<EdgeDeviceResponseApiSubscription> (instance, "variable 'instance' is a EdgeDeviceResponseApiSubscription");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ClientApplication'
        /// </summary>
        [Test]
        public void ClientApplicationTest()
        {
            // TODO unit test for the property 'ClientApplication'
        }
        /// <summary>
        /// Test the property 'Href'
        /// </summary>
        [Test]
        public void HrefTest()
        {
            // TODO unit test for the property 'Href'
        }

    }

}
