/* 
 * Netilion API Documentation
 *
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Netilion.Api.Api;
using Netilion.Api.Model;
using Netilion.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Netilion.Api.Test
{
    /// <summary>
    ///  Class for testing EventStatusBase
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EventStatusBaseTests
    {
        // TODO uncomment below to declare an instance variable for EventStatusBase
        //private EventStatusBase instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EventStatusBase
            //instance = new EventStatusBase();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EventStatusBase
        /// </summary>
        [Test]
        public void EventStatusBaseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EventStatusBase
            //Assert.IsInstanceOfType<EventStatusBase> (instance, "variable 'instance' is a EventStatusBase");
        }

        /// <summary>
        /// Test deserialize a EventStatusResponse from type EventStatusBase
        /// </summary>
        [Test]
        public void EventStatusResponseDeserializeFromEventStatusBaseTest()
        {
            // TODO uncomment below to test deserialize a EventStatusResponse from type EventStatusBase
            //Assert.IsInstanceOf<EventStatusBase>(JsonConvert.DeserializeObject<EventStatusBase>(new EventStatusResponse().ToJson()));
        }
        /// <summary>
        /// Test deserialize a EventStatusRequest from type EventStatusBase
        /// </summary>
        [Test]
        public void EventStatusRequestDeserializeFromEventStatusBaseTest()
        {
            // TODO uncomment below to test deserialize a EventStatusRequest from type EventStatusBase
            //Assert.IsInstanceOf<EventStatusBase>(JsonConvert.DeserializeObject<EventStatusBase>(new EventStatusRequest().ToJson()));
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

    }

}
