/* 
 * Netilion API Documentation
 *
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Netilion.Api.Api;
using Netilion.Api.Model;
using Netilion.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Netilion.Api.Test
{
    /// <summary>
    ///  Class for testing InstrumentationTypeBase
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InstrumentationTypeBaseTests
    {
        // TODO uncomment below to declare an instance variable for InstrumentationTypeBase
        //private InstrumentationTypeBase instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InstrumentationTypeBase
            //instance = new InstrumentationTypeBase();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InstrumentationTypeBase
        /// </summary>
        [Test]
        public void InstrumentationTypeBaseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InstrumentationTypeBase
            //Assert.IsInstanceOfType<InstrumentationTypeBase> (instance, "variable 'instance' is a InstrumentationTypeBase");
        }

        /// <summary>
        /// Test deserialize a InstrumentationTypeRequest from type InstrumentationTypeBase
        /// </summary>
        [Test]
        public void InstrumentationTypeRequestDeserializeFromInstrumentationTypeBaseTest()
        {
            // TODO uncomment below to test deserialize a InstrumentationTypeRequest from type InstrumentationTypeBase
            //Assert.IsInstanceOf<InstrumentationTypeBase>(JsonConvert.DeserializeObject<InstrumentationTypeBase>(new InstrumentationTypeRequest().ToJson()));
        }
        /// <summary>
        /// Test deserialize a InstrumentationTypeResponse from type InstrumentationTypeBase
        /// </summary>
        [Test]
        public void InstrumentationTypeResponseDeserializeFromInstrumentationTypeBaseTest()
        {
            // TODO uncomment below to test deserialize a InstrumentationTypeResponse from type InstrumentationTypeBase
            //Assert.IsInstanceOf<InstrumentationTypeBase>(JsonConvert.DeserializeObject<InstrumentationTypeBase>(new InstrumentationTypeResponse().ToJson()));
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

    }

}
