/* 
 * Netilion API Documentation
 *
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Netilion.Api.Api;
using Netilion.Api.Model;
using Netilion.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Netilion.Api.Test
{
    /// <summary>
    ///  Class for testing InstrumentationBase
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InstrumentationBaseTests
    {
        // TODO uncomment below to declare an instance variable for InstrumentationBase
        //private InstrumentationBase instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InstrumentationBase
            //instance = new InstrumentationBase();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InstrumentationBase
        /// </summary>
        [Test]
        public void InstrumentationBaseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InstrumentationBase
            //Assert.IsInstanceOfType<InstrumentationBase> (instance, "variable 'instance' is a InstrumentationBase");
        }

        /// <summary>
        /// Test deserialize a InstrumentationRequest from type InstrumentationBase
        /// </summary>
        [Test]
        public void InstrumentationRequestDeserializeFromInstrumentationBaseTest()
        {
            // TODO uncomment below to test deserialize a InstrumentationRequest from type InstrumentationBase
            //Assert.IsInstanceOf<InstrumentationBase>(JsonConvert.DeserializeObject<InstrumentationBase>(new InstrumentationRequest().ToJson()));
        }
        /// <summary>
        /// Test deserialize a InstrumentationResponse from type InstrumentationBase
        /// </summary>
        [Test]
        public void InstrumentationResponseDeserializeFromInstrumentationBaseTest()
        {
            // TODO uncomment below to test deserialize a InstrumentationResponse from type InstrumentationBase
            //Assert.IsInstanceOf<InstrumentationBase>(JsonConvert.DeserializeObject<InstrumentationBase>(new InstrumentationResponse().ToJson()));
        }

        /// <summary>
        /// Test the property 'Tag'
        /// </summary>
        [Test]
        public void TagTest()
        {
            // TODO unit test for the property 'Tag'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Criticality'
        /// </summary>
        [Test]
        public void CriticalityTest()
        {
            // TODO unit test for the property 'Criticality'
        }
        /// <summary>
        /// Test the property 'Accessibility'
        /// </summary>
        [Test]
        public void AccessibilityTest()
        {
            // TODO unit test for the property 'Accessibility'
        }

    }

}
