/* 
 * Netilion API Documentation
 *
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Netilion.Api.Api;
using Netilion.Api.Model;
using Netilion.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Netilion.Api.Test
{
    /// <summary>
    ///  Class for testing Links13
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Links13Tests
    {
        // TODO uncomment below to declare an instance variable for Links13
        //private Links13 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Links13
            //instance = new Links13();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Links13
        /// </summary>
        [Test]
        public void Links13InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Links13
            //Assert.IsInstanceOfType<Links13> (instance, "variable 'instance' is a Links13");
        }


        /// <summary>
        /// Test the property 'Instrumentations'
        /// </summary>
        [Test]
        public void InstrumentationsTest()
        {
            // TODO unit test for the property 'Instrumentations'
        }
        /// <summary>
        /// Test the property 'Assets'
        /// </summary>
        [Test]
        public void AssetsTest()
        {
            // TODO unit test for the property 'Assets'
        }
        /// <summary>
        /// Test the property 'Documents'
        /// </summary>
        [Test]
        public void DocumentsTest()
        {
            // TODO unit test for the property 'Documents'
        }
        /// <summary>
        /// Test the property 'Pictures'
        /// </summary>
        [Test]
        public void PicturesTest()
        {
            // TODO unit test for the property 'Pictures'
        }
        /// <summary>
        /// Test the property 'Specifications'
        /// </summary>
        [Test]
        public void SpecificationsTest()
        {
            // TODO unit test for the property 'Specifications'
        }
        /// <summary>
        /// Test the property 'Recipes'
        /// </summary>
        [Test]
        public void RecipesTest()
        {
            // TODO unit test for the property 'Recipes'
        }

    }

}
