/* 
 * Netilion API Documentation
 *
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Netilion.Api.Api;
using Netilion.Api.Model;
using Netilion.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Netilion.Api.Test
{
    /// <summary>
    ///  Class for testing SoftwareRequestPatch
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SoftwareRequestPatchTests
    {
        // TODO uncomment below to declare an instance variable for SoftwareRequestPatch
        //private SoftwareRequestPatch instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SoftwareRequestPatch
            //instance = new SoftwareRequestPatch();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SoftwareRequestPatch
        /// </summary>
        [Test]
        public void SoftwareRequestPatchInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SoftwareRequestPatch
            //Assert.IsInstanceOfType<SoftwareRequestPatch> (instance, "variable 'instance' is a SoftwareRequestPatch");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'VersionNumber'
        /// </summary>
        [Test]
        public void VersionNumberTest()
        {
            // TODO unit test for the property 'VersionNumber'
        }
        /// <summary>
        /// Test the property 'Tenant'
        /// </summary>
        [Test]
        public void TenantTest()
        {
            // TODO unit test for the property 'Tenant'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
