/* 
 * Netilion API Documentation
 *
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Netilion.Api.Api;
using Netilion.Api.Model;
using Netilion.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Netilion.Api.Test
{
    /// <summary>
    ///  Class for testing SpecificationBase
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SpecificationBaseTests
    {
        // TODO uncomment below to declare an instance variable for SpecificationBase
        //private SpecificationBase instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SpecificationBase
            //instance = new SpecificationBase();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SpecificationBase
        /// </summary>
        [Test]
        public void SpecificationBaseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SpecificationBase
            //Assert.IsInstanceOfType<SpecificationBase> (instance, "variable 'instance' is a SpecificationBase");
        }

        /// <summary>
        /// Test deserialize a SpecificationUIVisibleRequest from type SpecificationRequest
        /// </summary>
        [Test]
        public void SpecificationUIVisibleRequestDeserializeFromSpecificationRequestTest()
        {
            // TODO uncomment below to test deserialize a SpecificationUIVisibleRequest from type SpecificationRequest
            //Assert.IsInstanceOf<SpecificationRequest>(JsonConvert.DeserializeObject<SpecificationRequest>(new SpecificationUIVisibleRequest().ToJson()));
        }
        /// <summary>
        /// Test deserialize a SpecificationUIVisibleResponse from type SpecificationBase
        /// </summary>
        [Test]
        public void SpecificationUIVisibleResponseDeserializeFromSpecificationBaseTest()
        {
            // TODO uncomment below to test deserialize a SpecificationUIVisibleResponse from type SpecificationBase
            //Assert.IsInstanceOf<SpecificationBase>(JsonConvert.DeserializeObject<SpecificationBase>(new SpecificationUIVisibleResponse().ToJson()));
        }
        /// <summary>
        /// Test deserialize a SpecificationRequest from type SpecificationBase
        /// </summary>
        [Test]
        public void SpecificationRequestDeserializeFromSpecificationBaseTest()
        {
            // TODO uncomment below to test deserialize a SpecificationRequest from type SpecificationBase
            //Assert.IsInstanceOf<SpecificationBase>(JsonConvert.DeserializeObject<SpecificationBase>(new SpecificationRequest().ToJson()));
        }
        /// <summary>
        /// Test deserialize a SpecificationResponse from type SpecificationBase
        /// </summary>
        [Test]
        public void SpecificationResponseDeserializeFromSpecificationBaseTest()
        {
            // TODO uncomment below to test deserialize a SpecificationResponse from type SpecificationBase
            //Assert.IsInstanceOf<SpecificationBase>(JsonConvert.DeserializeObject<SpecificationBase>(new SpecificationResponse().ToJson()));
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'Unit'
        /// </summary>
        [Test]
        public void UnitTest()
        {
            // TODO unit test for the property 'Unit'
        }
        /// <summary>
        /// Test the property 'SourceTimestamp'
        /// </summary>
        [Test]
        public void SourceTimestampTest()
        {
            // TODO unit test for the property 'SourceTimestamp'
        }

    }

}
