/* 
 * Netilion API Documentation
 *
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Netilion.Api.Api;
using Netilion.Api.Model;
using Netilion.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Netilion.Api.Test
{
    /// <summary>
    ///  Class for testing SubscriptionSeatBase
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SubscriptionSeatBaseTests
    {
        // TODO uncomment below to declare an instance variable for SubscriptionSeatBase
        //private SubscriptionSeatBase instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SubscriptionSeatBase
            //instance = new SubscriptionSeatBase();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SubscriptionSeatBase
        /// </summary>
        [Test]
        public void SubscriptionSeatBaseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SubscriptionSeatBase
            //Assert.IsInstanceOfType<SubscriptionSeatBase> (instance, "variable 'instance' is a SubscriptionSeatBase");
        }

        /// <summary>
        /// Test deserialize a SubscriptionSeatResponse from type SubscriptionSeatBase
        /// </summary>
        [Test]
        public void SubscriptionSeatResponseDeserializeFromSubscriptionSeatBaseTest()
        {
            // TODO uncomment below to test deserialize a SubscriptionSeatResponse from type SubscriptionSeatBase
            //Assert.IsInstanceOf<SubscriptionSeatBase>(JsonConvert.DeserializeObject<SubscriptionSeatBase>(new SubscriptionSeatResponse().ToJson()));
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

    }

}
