/* 
 * Netilion API Documentation
 *
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Netilion.Api.Api;
using Netilion.Api.Model;
using Netilion.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Netilion.Api.Test
{
    /// <summary>
    ///  Class for testing TechnicalUserBase
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TechnicalUserBaseTests
    {
        // TODO uncomment below to declare an instance variable for TechnicalUserBase
        //private TechnicalUserBase instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TechnicalUserBase
            //instance = new TechnicalUserBase();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TechnicalUserBase
        /// </summary>
        [Test]
        public void TechnicalUserBaseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TechnicalUserBase
            //Assert.IsInstanceOfType<TechnicalUserBase> (instance, "variable 'instance' is a TechnicalUserBase");
        }

        /// <summary>
        /// Test deserialize a TechnicalUserCreateResponse from type TechnicalUserBase
        /// </summary>
        [Test]
        public void TechnicalUserCreateResponseDeserializeFromTechnicalUserBaseTest()
        {
            // TODO uncomment below to test deserialize a TechnicalUserCreateResponse from type TechnicalUserBase
            //Assert.IsInstanceOf<TechnicalUserBase>(JsonConvert.DeserializeObject<TechnicalUserBase>(new TechnicalUserCreateResponse().ToJson()));
        }
        /// <summary>
        /// Test deserialize a TechnicalUserRequest from type TechnicalUserBase
        /// </summary>
        [Test]
        public void TechnicalUserRequestDeserializeFromTechnicalUserBaseTest()
        {
            // TODO uncomment below to test deserialize a TechnicalUserRequest from type TechnicalUserBase
            //Assert.IsInstanceOf<TechnicalUserBase>(JsonConvert.DeserializeObject<TechnicalUserBase>(new TechnicalUserRequest().ToJson()));
        }
        /// <summary>
        /// Test deserialize a TechnicalUserResponse from type TechnicalUserBase
        /// </summary>
        [Test]
        public void TechnicalUserResponseDeserializeFromTechnicalUserBaseTest()
        {
            // TODO uncomment below to test deserialize a TechnicalUserResponse from type TechnicalUserBase
            //Assert.IsInstanceOf<TechnicalUserBase>(JsonConvert.DeserializeObject<TechnicalUserBase>(new TechnicalUserResponse().ToJson()));
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Disabled'
        /// </summary>
        [Test]
        public void DisabledTest()
        {
            // TODO unit test for the property 'Disabled'
        }

    }

}
