/* 
 * Netilion API Documentation
 *
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Netilion.Api.Api;
using Netilion.Api.Model;
using Netilion.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Netilion.Api.Test
{
    /// <summary>
    ///  Class for testing UserResponseLinks
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserResponseLinksTests
    {
        // TODO uncomment below to declare an instance variable for UserResponseLinks
        //private UserResponseLinks instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserResponseLinks
            //instance = new UserResponseLinks();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserResponseLinks
        /// </summary>
        [Test]
        public void UserResponseLinksInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserResponseLinks
            //Assert.IsInstanceOfType<UserResponseLinks> (instance, "variable 'instance' is a UserResponseLinks");
        }


        /// <summary>
        /// Test the property 'Usergroups'
        /// </summary>
        [Test]
        public void UsergroupsTest()
        {
            // TODO unit test for the property 'Usergroups'
        }
        /// <summary>
        /// Test the property 'Userroles'
        /// </summary>
        [Test]
        public void UserrolesTest()
        {
            // TODO unit test for the property 'Userroles'
        }
        /// <summary>
        /// Test the property 'Specifications'
        /// </summary>
        [Test]
        public void SpecificationsTest()
        {
            // TODO unit test for the property 'Specifications'
        }

    }

}
