/* 
 * Netilion API Documentation
 *
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Netilion.Api.Api;
using Netilion.Api.Model;
using Netilion.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Netilion.Api.Test
{
    /// <summary>
    ///  Class for testing WebhookEventResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WebhookEventResponseTests
    {
        // TODO uncomment below to declare an instance variable for WebhookEventResponse
        //private WebhookEventResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WebhookEventResponse
            //instance = new WebhookEventResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WebhookEventResponse
        /// </summary>
        [Test]
        public void WebhookEventResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WebhookEventResponse
            //Assert.IsInstanceOfType<WebhookEventResponse> (instance, "variable 'instance' is a WebhookEventResponse");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Payload'
        /// </summary>
        [Test]
        public void PayloadTest()
        {
            // TODO unit test for the property 'Payload'
        }
        /// <summary>
        /// Test the property 'LastSendAt'
        /// </summary>
        [Test]
        public void LastSendAtTest()
        {
            // TODO unit test for the property 'LastSendAt'
        }
        /// <summary>
        /// Test the property 'Retries'
        /// </summary>
        [Test]
        public void RetriesTest()
        {
            // TODO unit test for the property 'Retries'
        }

    }

}
