/* 
 * Netilion API Documentation
 *
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Netilion.Api.Client;
using Netilion.Api.Api;
using Netilion.Api.Model;

namespace Netilion.Api.Test
{
    /// <summary>
    ///  Class for testing DeliveryStatusApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class DeliveryStatusApiTests
    {
        private DeliveryStatusApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DeliveryStatusApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DeliveryStatusApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DeliveryStatusApi
            //Assert.IsInstanceOfType(typeof(DeliveryStatusApi), instance, "instance is a DeliveryStatusApi");
        }

        /// <summary>
        /// Test CreateDeliveryStatus
        /// </summary>
        [Test]
        public void CreateDeliveryStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DeliveryStatusRequest body = null;
            //var response = instance.CreateDeliveryStatus(body);
            //Assert.IsInstanceOf<DeliveryStatusRequest> (response, "response is DeliveryStatusRequest");
        }
        /// <summary>
        /// Test DeleteDeliveryStatus
        /// </summary>
        [Test]
        public void DeleteDeliveryStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //instance.DeleteDeliveryStatus(id);
            
        }
        /// <summary>
        /// Test GetDeliveryIdStatus
        /// </summary>
        [Test]
        public void GetDeliveryIdStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? deliveryId = null;
            //string include = null;
            //string acceptLanguage = null;
            //var response = instance.GetDeliveryIdStatus(deliveryId, include, acceptLanguage);
            //Assert.IsInstanceOf<DeliveryStatusResponse> (response, "response is DeliveryStatusResponse");
        }
        /// <summary>
        /// Test GetDeliveryStatusById
        /// </summary>
        [Test]
        public void GetDeliveryStatusByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //string acceptLanguage = null;
            //var response = instance.GetDeliveryStatusById(id, acceptLanguage);
            //Assert.IsInstanceOf<DeliveryStatusResponse> (response, "response is DeliveryStatusResponse");
        }
        /// <summary>
        /// Test GetDeliveryStatuses
        /// </summary>
        [Test]
        public void GetDeliveryStatusesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? perPage = null;
            //string code = null;
            //string name = null;
            //string tenantId = null;
            //string orderBy = null;
            //string acceptLanguage = null;
            //var response = instance.GetDeliveryStatuses(page, perPage, code, name, tenantId, orderBy, acceptLanguage);
            //Assert.IsInstanceOf<DeliveryStatuses> (response, "response is DeliveryStatuses");
        }
        /// <summary>
        /// Test UpdateDeliveryStatuses
        /// </summary>
        [Test]
        public void UpdateDeliveryStatusesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DeliveryStatusRequest body = null;
            //long? id = null;
            //string contentLanguage = null;
            //instance.UpdateDeliveryStatuses(body, id, contentLanguage);
            
        }
    }

}
