/* 
 * Netilion API Documentation
 *
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Netilion.Api.Client;
using Netilion.Api.Api;
using Netilion.Api.Model;

namespace Netilion.Api.Test
{
    /// <summary>
    ///  Class for testing NodeTypeApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class NodeTypeApiTests
    {
        private NodeTypeApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new NodeTypeApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NodeTypeApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' NodeTypeApi
            //Assert.IsInstanceOfType(typeof(NodeTypeApi), instance, "instance is a NodeTypeApi");
        }

        /// <summary>
        /// Test CreateNodeType
        /// </summary>
        [Test]
        public void CreateNodeTypeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //NodeTypeRequest body = null;
            //var response = instance.CreateNodeType(body);
            //Assert.IsInstanceOf<NodeTypeResponse> (response, "response is NodeTypeResponse");
        }
        /// <summary>
        /// Test DeleteNodeType
        /// </summary>
        [Test]
        public void DeleteNodeTypeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //instance.DeleteNodeType(id);
            
        }
        /// <summary>
        /// Test GetNodeIdType
        /// </summary>
        [Test]
        public void GetNodeIdTypeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? nodeId = null;
            //string include = null;
            //string acceptLanguage = null;
            //var response = instance.GetNodeIdType(nodeId, include, acceptLanguage);
            //Assert.IsInstanceOf<NodeTypeResponse> (response, "response is NodeTypeResponse");
        }
        /// <summary>
        /// Test GetNodeTypeById
        /// </summary>
        [Test]
        public void GetNodeTypeByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //string include = null;
            //string acceptLanguage = null;
            //var response = instance.GetNodeTypeById(id, include, acceptLanguage);
            //Assert.IsInstanceOf<NodeTypeResponse> (response, "response is NodeTypeResponse");
        }
        /// <summary>
        /// Test GetNodeTypes
        /// </summary>
        [Test]
        public void GetNodeTypesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? perPage = null;
            //string include = null;
            //string name = null;
            //string code = null;
            //string tenantId = null;
            //string parentId = null;
            //string orderBy = null;
            //string acceptLanguage = null;
            //var response = instance.GetNodeTypes(page, perPage, include, name, code, tenantId, parentId, orderBy, acceptLanguage);
            //Assert.IsInstanceOf<NodeTypes> (response, "response is NodeTypes");
        }
        /// <summary>
        /// Test GetNodeTypesOptions
        /// </summary>
        [Test]
        public void GetNodeTypesOptionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? nodeId = null;
            //int? page = null;
            //int? perPage = null;
            //string tenantId = null;
            //string name = null;
            //string code = null;
            //string acceptLanguage = null;
            //var response = instance.GetNodeTypesOptions(nodeId, page, perPage, tenantId, name, code, acceptLanguage);
            //Assert.IsInstanceOf<NodeTypes> (response, "response is NodeTypes");
        }
        /// <summary>
        /// Test UpdateNodeType
        /// </summary>
        [Test]
        public void UpdateNodeTypeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //NodeTypeRequest body = null;
            //long? id = null;
            //string contentLanguage = null;
            //instance.UpdateNodeType(body, id, contentLanguage);
            
        }
    }

}
