/* 
 * Netilion API Documentation
 *
 * Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API. Please visit our developer portal for further instructions and information: https://developer.netilion.endress.com/ 
 *
 * OpenAPI spec version: 01.00.00
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Netilion.Api.Client;
using Netilion.Api.Api;
using Netilion.Api.Model;

namespace Netilion.Api.Test
{
    /// <summary>
    ///  Class for testing SparePartTypeApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SparePartTypeApiTests
    {
        private SparePartTypeApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SparePartTypeApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SparePartTypeApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SparePartTypeApi
            //Assert.IsInstanceOfType(typeof(SparePartTypeApi), instance, "instance is a SparePartTypeApi");
        }

        /// <summary>
        /// Test CreateSparePartType
        /// </summary>
        [Test]
        public void CreateSparePartTypeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SparePartTypeRequest body = null;
            //var response = instance.CreateSparePartType(body);
            //Assert.IsInstanceOf<SparePartTypeResponse> (response, "response is SparePartTypeResponse");
        }
        /// <summary>
        /// Test DeleteSparePartType
        /// </summary>
        [Test]
        public void DeleteSparePartTypeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //instance.DeleteSparePartType(id);
            
        }
        /// <summary>
        /// Test GetSparePartTypeById
        /// </summary>
        [Test]
        public void GetSparePartTypeByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //string include = null;
            //string acceptLanguage = null;
            //var response = instance.GetSparePartTypeById(id, include, acceptLanguage);
            //Assert.IsInstanceOf<SparePartTypeResponse> (response, "response is SparePartTypeResponse");
        }
        /// <summary>
        /// Test GetSparePartTypes
        /// </summary>
        [Test]
        public void GetSparePartTypesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? perPage = null;
            //string name = null;
            //string code = null;
            //string tenantId = null;
            //string orderBy = null;
            //string acceptLanguage = null;
            //var response = instance.GetSparePartTypes(page, perPage, name, code, tenantId, orderBy, acceptLanguage);
            //Assert.IsInstanceOf<SparePartTypes> (response, "response is SparePartTypes");
        }
        /// <summary>
        /// Test GetSparePartTypesOptions
        /// </summary>
        [Test]
        public void GetSparePartTypesOptionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? sparePartId = null;
            //int? page = null;
            //int? perPage = null;
            //string name = null;
            //string tenantId = null;
            //string code = null;
            //string orderBy = null;
            //string acceptLanguage = null;
            //var response = instance.GetSparePartTypesOptions(sparePartId, page, perPage, name, tenantId, code, orderBy, acceptLanguage);
            //Assert.IsInstanceOf<SparePartTypes> (response, "response is SparePartTypes");
        }
        /// <summary>
        /// Test UpdateSparePartType
        /// </summary>
        [Test]
        public void UpdateSparePartTypeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SparePartTypeRequest body = null;
            //long? id = null;
            //string contentLanguage = null;
            //instance.UpdateSparePartType(body, id, contentLanguage);
            
        }
    }

}
